import { Item } from "../../../domain/entities";

export const CATEGORIES: string[] = [
  "Electrónica",
  "Celulares y Smartphones",
  "Computación",
  "Televisores y Video",
  "Consolas y Videojuegos",
  "Audio",
  "Cámaras y Fotografía",
  "Electrodomésticos",
  "Hogar y Muebles",
  "Decoración",
  "Cocina",
  "Herramientas y Construcción",
  "Deportes y Fitness",
  "Ropa, Zapatos y Accesorios",
  "Juguetes y Bebés",
  "Salud y Belleza",
  "Libros, Música y Películas",
  "Autos y Motocicletas",
  "Mascotas",
  "Instrumentos Musicales",
];

export const ITEMS: Item[] = [
  new Item(
    "1",
    "Auriculares Inalámbricos",
    { currency: "USD", amount: 99, decimals: 99 },
    "https://example.com/images/headphones.jpg",
    "new",
    true,
    120,
    "Auriculares inalámbricos de alta calidad con cancelación de ruido.",
  ),
  new Item(
    "2",
    "Mouse para Gaming",
    { currency: "USD", amount: 49, decimals: 50 },
    "https://example.com/images/mouse.jpg",
    "used",
    false,
    45,
    "Mouse ergonómico para gaming con iluminación RGB personalizable.",
  ),
  new Item(
    "3",
    "Teclado Mecánico",
    { currency: "USD", amount: 150, decimals: 0 },
    "https://example.com/images/keyboard.jpg",
    "new",
    true,
    75,
    "Teclado mecánico duradero con interruptores táctiles.",
  ),
  new Item(
    "4",
    "Reloj Inteligente",
    { currency: "USD", amount: 199, decimals: 99 },
    "https://example.com/images/smartwatch.jpg",
    "new",
    true,
    200,
    "Reloj inteligente con muchas funciones, monitor de ritmo cardíaco y GPS.",
  ),
  new Item(
    "5",
    "Soporte para Laptop",
    { currency: "USD", amount: 29, decimals: 99 },
    "https://example.com/images/laptop-stand.jpg",
    "new",
    false,
    300,
    "Soporte ajustable para laptop hecho de aleación de aluminio.",
  ),
  new Item(
    "6",
    "Altavoz Bluetooth",
    { currency: "USD", amount: 59, decimals: 95 },
    "https://example.com/images/speaker.jpg",
    "new",
    true,
    180,
    "Altavoz Bluetooth portátil con batería de 12 horas.",
  ),
  new Item(
    "7",
    "Disco Duro Externo",
    { currency: "USD", amount: 89, decimals: 0 },
    "https://example.com/images/hard-drive.jpg",
    "new",
    false,
    150,
    "Disco duro externo de 1TB con conectividad USB 3.0.",
  ),
  new Item(
    "8",
    "Cámara de Acción",
    { currency: "USD", amount: 129, decimals: 99 },
    "https://example.com/images/action-camera.jpg",
    "used",
    true,
    60,
    "Cámara de acción compacta con grabación 4K y diseño resistente al agua.",
  ),
  new Item(
    "9",
    "Trípode para Smartphone",
    { currency: "USD", amount: 25, decimals: 50 },
    "https://example.com/images/tripod.jpg",
    "new",
    true,
    95,
    "Trípode flexible para smartphones para fotografía y grabación de video.",
  ),
  new Item(
    "10",
    "Auriculares con Cancelación de Ruido",
    { currency: "USD", amount: 79, decimals: 99 },
    "https://example.com/images/earbuds.jpg",
    "new",
    true,
    110,
    "Auriculares inalámbricos con cancelación activa de ruido y larga duración de batería.",
  ),
  new Item(
    "11",
    "Cargador Portátil",
    { currency: "USD", amount: 39, decimals: 99 },
    "https://example.com/images/portable-charger.jpg",
    "new",
    true,
    220,
    "Cargador portátil de 10000mAh para smartphones y tablets.",
  ),
  new Item(
    "12",
    "Pulsera de Actividad",
    { currency: "USD", amount: 69, decimals: 50 },
    "https://example.com/images/fitness-tracker.jpg",
    "new",
    true,
    140,
    "Pulsera de actividad impermeable con monitoreo de ritmo cardíaco y sueño.",
  ),
  new Item(
    "13",
    "Cámara Digital",
    { currency: "USD", amount: 299, decimals: 0 },
    "https://example.com/images/digital-camera.jpg",
    "used",
    false,
    50,
    "Cámara digital compacta con sensor de 20MP y zoom óptico 5x.",
  ),
  new Item(
    "14",
    "Lámpara de Escritorio LED",
    { currency: "USD", amount: 45, decimals: 99 },
    "https://example.com/images/desk-lamp.jpg",
    "new",
    false,
    180,
    "Lámpara de escritorio LED ajustable con control táctil y opciones de atenuación.",
  ),
  new Item(
    "15",
    "Casco de Realidad Virtual",
    { currency: "USD", amount: 399, decimals: 99 },
    "https://example.com/images/vr-headset.jpg",
    "new",
    true,
    80,
    "Casco de realidad virtual inmersivo compatible con PC y consolas de videojuegos.",
  ),
  new Item(
    "16",
    "Monitor LED",
    { currency: "USD", amount: 179, decimals: 99 },
    "https://example.com/images/monitor.jpg",
    "new",
    true,
    90,
    "Monitor LED de 24 pulgadas con resolución Full HD y entrada HDMI.",
  ),
  new Item(
    "17",
    "Teclado Inalámbrico",
    { currency: "USD", amount: 49, decimals: 99 },
    "https://example.com/images/wireless-keyboard.jpg",
    "new",
    true,
    130,
    "Teclado inalámbrico compacto con batería de larga duración y teclas silenciosas.",
  ),
  new Item(
    "18",
    "Ratón Inalámbrico",
    { currency: "USD", amount: 29, decimals: 99 },
    "https://example.com/images/wireless-mouse.jpg",
    "new",
    false,
    210,
    "Ratón inalámbrico ergonómico con receptor USB de alta precisión.",
  ),
  new Item(
    "19",
    "Auriculares Deportivos",
    { currency: "USD", amount: 59, decimals: 50 },
    "https://example.com/images/sports-headphones.jpg",
    "new",
    true,
    160,
    "Auriculares deportivos resistentes al sudor con sonido de alta calidad.",
  ),
  new Item(
    "20",
    "Proyector Portátil",
    { currency: "USD", amount: 249, decimals: 99 },
    "https://example.com/images/portable-projector.jpg",
    "new",
    true,
    70,
    "Proyector portátil con resolución HD y conectividad HDMI y USB.",
  ),
  new Item(
    "21",
    "Cámara Web HD",
    { currency: "USD", amount: 69, decimals: 99 },
    "https://example.com/images/webcam.jpg",
    "new",
    true,
    110,
    "Cámara web HD con micrófono integrado y enfoque automático.",
  ),
  new Item(
    "22",
    "Micrófono de Condensador",
    { currency: "USD", amount: 129, decimals: 99 },
    "https://example.com/images/condensor-mic.jpg",
    "new",
    true,
    85,
    "Micrófono de condensador profesional ideal para streaming y grabación.",
  ),
  new Item(
    "23",
    "Tablet 10 Pulgadas",
    { currency: "USD", amount: 199, decimals: 50 },
    "https://example.com/images/tablet.jpg",
    "new",
    true,
    140,
    "Tablet de 10 pulgadas con pantalla táctil, almacenamiento de 64GB y Wi-Fi.",
  ),
  new Item(
    "24",
    "Teclado Musical MIDI",
    { currency: "USD", amount: 149, decimals: 99 },
    "https://example.com/images/midi-keyboard.jpg",
    "new",
    true,
    75,
    "Teclado MIDI con 49 teclas sensibles a la velocidad y conectividad USB.",
  ),
  new Item(
    "25",
    "Altavoces de Estantería",
    { currency: "USD", amount: 89, decimals: 99 },
    "https://example.com/images/bookshelf-speakers.jpg",
    "new",
    false,
    60,
    "Altavoces de estantería compactos con sonido nítido y graves profundos.",
  ),
  new Item(
    "26",
    "Router Wi-Fi 6",
    { currency: "USD", amount: 159, decimals: 99 },
    "https://example.com/images/wifi-router.jpg",
    "new",
    true,
    90,
    "Router Wi-Fi 6 de alta velocidad con cobertura ampliada y múltiples bandas.",
  ),
  new Item(
    "27",
    "Disco SSD Externo",
    { currency: "USD", amount: 129, decimals: 50 },
    "https://example.com/images/ssd-external.jpg",
    "new",
    true,
    120,
    "Disco SSD externo de 500GB con conectividad USB-C rápida y portátil.",
  ),
  new Item(
    "28",
    "Cámara Instantánea",
    { currency: "USD", amount: 99, decimals: 99 },
    "https://example.com/images/instant-camera.jpg",
    "new",
    true,
    80,
    "Cámara instantánea compacta para fotos al instante con diseño retro.",
  ),
  new Item(
    "29",
    "Auriculares Gaming RGB",
    { currency: "USD", amount: 79, decimals: 99 },
    "https://example.com/images/gaming-headset.jpg",
    "new",
    true,
    100,
    "Auriculares para gaming con iluminación RGB, micrófono y sonido envolvente.",
  ),
  new Item(
    "30",
    "Soporte de Micrófono Ajustable",
    { currency: "USD", amount: 39, decimals: 99 },
    "https://example.com/images/mic-stand.jpg",
    "new",
    false,
    150,
    "Soporte de micrófono ajustable compatible con estudios de grabación y streaming.",
  ),
];
